### PR TITLE
fix!: remove duplicate Value field from ResolutionDetail structs

### LINKED ISSUE #57: [BUG] Typed ResolutionDetail structs have mulitple different `Value` values
### Observed behavior

Looking at https://github.com/open-feature/golang-sdk/blob/main/pkg/openfeature/provider.go#L65-L68 and running the code, it is possible for a provider to return a struct for `BoolResolutionDetail` where there are two different `Value` elements, with different values.

eg
image

It's been a while since I've done go coding, and this may be idiomatic, but to me it's confusing

### Expected Behavior

You should only be able to set one `Value` value

### Steps to reproduce

```go
	thing := openfeature.BoolResolutionDetail{
		Value: true,
		ResolutionDetail: openfeature.ResolutionDetail{
			Value: false,
		},
	}
```

### PR DESCRIPTION
**Pull request by skyerus**
Fixes #57

### CODE REVIEW

File: pkg/openfeature/provider.go [hunk 1]
```diff
@@ -16,10 +16,10 @@ const (
...
 type FeatureProvider interface {
 	Metadata() Metadata
-	BooleanEvaluation(flag string, defaultValue bool, evalCtx map[string]interface{}) BoolResolutionDetail
-	StringEvaluation(flag string, defaultValue string, evalCtx map[string]interface{}) StringResolutionDetail
-	FloatEvaluation(flag string, defaultValue float64, evalCtx map[string]interface{}) FloatResolutionDetail
-	IntEvaluation(flag string, defaultValue int64, evalCtx map[string]interface{}) IntResolutionDetail
+	BooleanEvaluation(flag string, defaultValue bool, evalCtx map[string]interface{}) ResolutionDetail
+	StringEvaluation(flag string, defaultValue string, evalCtx map[string]interface{}) ResolutionDetail
+	FloatEvaluation(flag string, defaultValue float64, evalCtx map[string]interface{}) ResolutionDetail
+	IntEvaluation(flag string, defaultValue int64, evalCtx map[string]interface{}) ResolutionDetail
```
Comment (agentgonzo) [inline pkg/openfeature/provider.go:22]: It was nice having the typed ResolutionDetail where the `Value` was typed. That way, when you called `getBooleanValue(...)` (or getBooleanDetail) you got a `boolean` value back, rather than a generic `interface{}`. It would be nice if we could keep this.

Wolud a possible fix be to make `ResolutionDetail` abstract (if that's even a thing in go) and remove the `Value: interface{}` from there, and keep the typed version in BoolResolutionValue etc?

Comment (skyerus) [reply pkg/openfeature/provider.go]: Good suggestion, done :)

**Review by james-milligan — APPROVED** [review]

**Review by agentgonzo — APPROVED** [review]
